# 1. Numpy Intro

In [1]:
import numpy as np

In [2]:
np.random.seed(1337)

# 1.1. Basics of Matrices

In [4]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [5]:
y = np.array([[1, 4, 7],
              [9, 2, 7]])
y

array([[1, 4, 7],
       [9, 2, 7]])

In [7]:
x.shape

(3,)

In [8]:
y.shape

(2, 3)

In [9]:
z = np.array([[1, 4, 3]]) # What's the difference?

In [10]:
z.shape

(1, 3)

In [11]:
z = np.arange(1, 2000, 1) # start, end, step
z[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
z.shape

(1999,)

In [14]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [18]:
np.arange(0.5, 10, 1)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [19]:
np.arange(0.5, 10, 1).shape

(10,)

In [20]:
np.arange(0.5, 10, 1).reshape(5, 2)

array([[0.5, 1.5],
       [2.5, 3.5],
       [4.5, 5.5],
       [6.5, 7.5],
       [8.5, 9.5]])

In [21]:
np.arange(0.5, 10, 1).reshape(5, 2).shape

(5, 2)

In [24]:
np.arange(0.5, 10, 1).reshape(5, 3).shape  # what's the error?

ValueError: cannot reshape array of size 10 into shape (5,3)

In [25]:
# Evenly spaced but we don't know the step
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [26]:
print(x)
print(x[1])
print(x[1:])

[1 4 3]
4
[4 3]


In [27]:
print(y)
y[0, 1] # this is extra in numpy

[[1 4 7]
 [9 2 7]]


4

In [29]:
y[:, 1] # all rows and first col

array([4, 2])

this return a Rank 1 tensor!

In [30]:
y[:, [1, 2]] # all rows and col no 1 & 2

array([[4, 7],
       [2, 7]])

# 1.2. Matrix Operations

In [31]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

so default step is 1!

In [34]:
a.shape

(6,)

In [35]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [36]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

In [39]:
a[1:4] = [9, 8, 7]
a

array([1, 9, 8, 7, 5, 6])

In [40]:
# This is most useful
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 1] = 4
b

array([[1., 2.],
       [0., 4.]])

In [41]:
b.shape

(2, 2)

# 1.3. Array Operations

In [42]:
print(b)

[[1. 2.]
 [0. 4.]]


In [43]:
b + 2

array([[3., 4.],
       [2., 6.]])

In [44]:
2 * b

array([[2., 4.],
       [0., 8.]])

In [45]:
b ** 2

array([[ 1.,  4.],
       [ 0., 16.]])

In [46]:
sum(b)

array([1., 6.])

default `sum()` func of python do col vise sum on np array

In [47]:
b.sum()

7.0

In [48]:
b.sum(axis=0)

array([1., 6.])

In [49]:
b.sum(axis=1)

array([3., 4.])

It's always return Rank 1 tensor

In [50]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [51]:
print(b)
print(d)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [52]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [53]:
b * d

array([[ 3,  8],
       [15, 24]])

This is element vise product

In [54]:
b.dot(d)

array([[13, 16],
       [29, 36]])

This is dot product

In [56]:
print(b)
print(d)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [55]:
b ** d

array([[   1,   16],
       [ 243, 4096]])

In [58]:
b.T # transpose

array([[1, 3],
       [2, 4]])

In [59]:
a

array([1, 9, 8, 7, 5, 6])

In [60]:
a.T

array([1, 9, 8, 7, 5, 6])

In [61]:
a.shape

(6,)

In [62]:
a.T.shape

(6,)

So, Rank 1 tensor has no dimension \
To solve this problem we can do following

In [63]:
a.reshape(6, 1).T

array([[1, 9, 8, 7, 5, 6]])

In [64]:
a.reshape(6,1).T.shape

(1, 6)

In [65]:
# Numpy has "broadcasting" or "mapping" functions
print(np.sqrt(36))

# works on both scalars and arrays
x = [1, 4, 9, 16]
np.sqrt(x)

6.0


array([1., 2., 3., 4.])

In [66]:
np.sqrt(36).shape

()

In [67]:
# checking conditions
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [68]:
x > 3

array([False, False,  True,  True,  True, False])

In [69]:
x > y

array([ True, False,  True,  True,  True, False])

So, this is element vise comparison

# 2. Misc Operations with Numpy

In [70]:
import math
def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Returns:
    s -- sigmoid(x)
    """

    s = 1. / ( 1. + math.e ** (-x))

    return s

In [73]:
basic_sigmoid(-1)

0.2689414213699951

In [74]:
basic_sigmoid(0)

0.5

In [75]:
basic_sigmoid(math.inf)

1.0

In [76]:
x = [-1, 0, 3]
basic_sigmoid(x) # Why

TypeError: bad operand type for unary -: 'list'

In [81]:
x = np.array(x)
basic_sigmoid(x)

array([0.26894142, 0.5       , 0.95257413])

In [82]:
x = [-1, 0, 3]
np.apply_along_axis(basic_sigmoid, arr=x, axis=0)

array([0.26894142, 0.5       , 0.95257413])